### ISSUE TITLE
Opening error on few of the users

### ISSUE THREAD

**Issue by BaturayOnural** [kasirgalabs/Tilki#11]
Some of the users (~%4) could not be able to run _Tilki_. 
Problem occurs when user tries to run the program after decompressing the zip. Unfortunately there was no error message. It just doesn't open.
It also unexpectedly opens and runs properly when it opened from the zip file.

**Comment by RootG** [comment]
No problems reported so far. This maybe related to #7. Closing issue until this situation happens again or can be reproduced.
