### ISSUE TITLE
DLL is missing error on Windows platform.

### ISSUE THREAD

**Issue by RootG** [kasirgalabs/Tilki#7]
If the application build as an image only package and the user does not have MSVCR100.dll in (s)he's
System32 folder, launcher crashes.

**Comment by BaturayOnural** [comment]
Are we sure that this problem happened because of the user?

**Comment by RootG** [comment]
An ![image](https://cloud.githubusercontent.com/assets/17679464/20609195/fa4864f4-b291-11e6-9753-bf17189ec42e.jpg) received from a user that sees this error. It obvious that he does not have required dll with the application. Either he removed the dll or did not received it with the application. There could be a chance that we missed the include the dll.

I couldn't reproduce the error by removing dll from the application directory and removing it from System32 folder.

**Comment by RootG** [comment]
I am closing this issue since we haven't seen any missing DLL error so far.
